# We're almost done, I Promise:

We learned in the last document that callbacks are the way we deal with IO bound work in systems based on event loops. However, we also learned that callbacks don't scale well, they very quickly get unwieldy when nesting occurs.

Well the smart people behind javascript came up with an abstraction on top of the chained callback pattern. This abstraction takes the form of an object called a promise.

```
Simply put, the promise object represents some work that is currently happening which will complete at some point in the future. We call special methods on the promise object to register callback functions that will be run when the work represented by the promise completes
```

Confused yet? Don't worry, asynchronous programming is one of the hardest topics to wrap your head around. Even aync veterans make mistakes.

So we know that a promise represents some work that is going on somewhere, whether it is cpu bound or IO bound (although usually it's IO bound, theres not a lot of point in using promises with cpu bound work). Well work can be in different states right? In particular it can be in any of the following:

- running (pending)
- completed successfully (fulfilled)
- completed with an error (rejected)

Since a promise represents some work that's happening it can also be in any of the states above, the names of the promisee states are in parentheses.

Ok, so far our promise object looks something like this:

```javascript
{
	state: 'pending', // this can be one of pending, fullfilled, or rejected
}
```

So far so good. So what happens if the work represented by the promise completes successfully? Well the promise is set to the fullfilled state. If the work represented by the promise returns any data a result property is set on the promise with the result of the work:

```javascript
{
	state: 'fulfilled',
	result: "I'm the result of some successful work",
}
```

Well what happens if the work represented by the promise fails? If you said the status of the promise gets set to rejected, and the error returned from the work is assigned to the result value, your absolutley correct!

```javascript
{
    state: 'rejected',
	result: "I'm the result of an error while doing work",
}
```

Ok, so where do callbacks fit into all this? Well if you remember from the last document, we want callbacks to run **after** the work is done. If we're talking about IO bound operations, we need the IO bound work to finish before calling our callback with the result.

Well it turns out that promises have two very important functions we haven't talked about: the .then() and .catch() functions. The .then function allows you to register optional success and failure callbacks to be run after the promise resolves (is rejected or fulfilled). .catch is kind of like .then, but it only allows you to register callbacks for when a function fails. So our promise object now looks like this:

```javascript
{
    state: 'rejected',
	result: "I'm the result of an error while doing work",
    then(onFulfilled, onRejected) {
        // If this promise is fulfilled call onFulfilled with the
        // result, otherwise call onRejected with the result
    },
    catch(onRejected) {
        // If this promise is rejected call onRejected with the result
    }
}
```

What is intersting to note, is that both .then and .catch return new promises (they're immutable which means the original promise is unaffected). This means that the .then and .catch operators can be chained.

Enough theory, let's look at some examples!

```javascript
// Lets assume that the function makeHTTPCall returns a promise that resolves with some json data if it's successful, or an error object if it fails

makeHTTPCall()
	.then(
		(data) => {
			return JSON.parse(data);
		},
		(err) => {
			console.warn('Uh oh, something broke');
		}
	)
	.then((json) => {
		console.log(json);
	});
```

So whats happening here? We are calling a function named makeHTTPCall, that returns a promise, this promise represents an HTTP call that is in progress. When/If the promise completes successfully it will pass the result data to the first callback which returns a parsed json object. The next callback in the then chain is called and is passed the parsed json, this callback simply logs it to the console.

If however the makeHTTPCall promise fails, the error callback from the first then will get called. Since there is no error handler for the second then function, execution will stop here.

**IMPORTANT: the callback functions run in a different context than the main fucntion, what this means is that execution will continue in the main file after the promise is created, only after the promise is completed will the callback functions be called**

## Lets make some promises

We can actually create our own promises, it's not too hard to do. A promise is just a regular old javascript object, and can be created just like any other javascript object:

```javascript
const p = new Promise((res, rej) => {});
```

You see the parameter to the promise constructor? It's a function! In fact both of arguments to the function are functions themselves: res is a function we can call when we want to tell the promise to be fulfilled, and rej is the function we can call when we want to tell the promise to be rejected. If we pass a value to res or rej that value will be set as the result parameter.

```javascript
// The following promise will be fulfilled with the value 'Hello World'
const f = new Promise((res) => res('Hello world'));

// The following promise will be rejected with the value 'Error'
const r = new Promise((_, rej) => rej('Hello World'));

// The following promise will fulfill if the value of test is true, otherwise it will be rejected
const test = false;
const fr = new Promise((res, rej) => {
	if (test) res();
	else rej();
});
```

## Don't break your promises:

So promises are super cool, but they have one fatal flaw: NESTING. Thats right, nesting .then statements inside other .then statements can get really clunky and confusing. Consider our earlier example of the HTTP call promise, what if we wanted to call an operation that returns a promise insde of a .then function

```javascript
// Lets assume that the function makeHTTPCall returns a promise that resolves with some json data if it's successful, or an error object if it fails. Let's also assume that writeToDatabase also returns a promise

makeHTTPCall()
	.then(
		(data) => {
			return JSON.parse(data);
		},
		(err) => {
			console.warn('Uh oh, something broke');
		}
	)
	.then((json) => {
		writeToDatabase.then((resp) => {
			console.log('Write to databse');
		});
	});
```

as you can see the nested.then is alredy ugly, now assume we had 5 or 6 nested operations, it can get really out of hand.

Well the smart people behind javascript noticed this, and came up with some syntactic sugar (or rather stole it from another language) that makes working with promises as easy as writing synchronous code. This syntactic sugar is async/await
